### ISSUE TITLE
Getting errors during the catkin build

### ISSUE THREAD

**Issue by gforestier27** [rpng/ov_maplab#5]
I'm getting theses errors when entering `catkin build maplab ov_maplab ov_data -j4` into the docker. 

```Errors     << maplab_console:make /catkin_ws/logs/maplab_console/build.make.001.log
/catkin_ws/devel/lib/libdepth_integration.so: undefined reference to `void backend::addLabelToPointCloud<resources::VoxbloxColorPointCloud>(unsigned int, unsigned long, resources::VoxbloxColorPointCloud*)'
collect2: error: ld returned 1 exit status
make[2]: *** [/catkin_ws/devel/lib/maplab_console/batch_runner] Error 1
make[1]: *** [CMakeFiles/batch_runner.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/catkin_ws/devel/lib/libdepth_integration.so: undefined reference to `void backend::addLabelToPointCloud<resources::VoxbloxColorPointCloud>(unsigned int, unsigned long, resources::VoxbloxColorPointCloud*)'
collect2: error: ld returned 1 exit status
make[2]: *** [/catkin_ws/devel/lib/maplab_console/maplab_console] Error 1
make[1]: *** [CMakeFiles/maplab_console.dir/all] Error 2
make: *** [all] Error 2
cd /catkin_ws/build/maplab_console; catkin build --get-env maplab_console | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
.............................................................................................................................................................................................
Failed     << maplab_console:make                             [ Exited with code 2 ]
Failed    <<< maplab_console                                  [ 56.2 seconds ]
Abandoned <<< vi_map_basic_plugin                             [ Unrelated job failed ]
Abandoned <<< vi_map_visualization_plugin                     [ Unrelated job failed ]
Abandoned <<< map_sparsification_plugin                       [ Unrelated job failed ]
Abandoned <<< localization_summary_map                        [ Unrelated job failed ]
Abandoned <<< loop_closure_handler                            [ Unrelated job failed ]
Abandoned <<< map_anchoring                                   [ Unrelated job failed ]
Abandoned <<< map_anchoring_plugin                            [ Unrelated job failed ]
Abandoned <<< map_optimization                                [ Unrelated job failed ]
Abandoned <<< localization_evaluator                          [ Unrelated job failed ]
Abandoned <<< loop_closure_plugin                             [ Unrelated job failed ]
Abandoned <<< map_optimization_plugin                         [ Unrelated job failed ]
Abandoned <<< mapping_workflows_plugin                        [ Unrelated job failed ]
Abandoned <<< pose_graph_manipulation_plugin                  [ Unrelated job failed ]
Abandoned <<< vi_map_summarization_plugin                     [ Unrelated job failed ]
Abandoned <<< maplab_server_node                              [ Unrelated job failed ]
Abandoned <<< vio_common                                      [ Unrelated job failed ]
Abandoned <<< localization_fusion                             [ Unrelated job failed ]
Abandoned <<< online_map_builders                             [ Unrelated job failed ]
Abandoned <<< maplab_node                                     [ Unrelated job failed ]
Abandoned <<< ov_maplab                                       [ Unrelated job failed ]
Abandoned <<< rovioli                                         [ Unrelated job failed ]
_____________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << map_sparsification:make /catkin_ws/logs/map_sparsification/build.make.001.log
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: map-sparsification/keyframing-heuristics-options.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' to specify a syntax version. (Defaulted to proto2 syntax.)
/catkin_ws/build/map_sparsification/compiled_proto/map-sparsification/keyframing-heuristics-options.pb.cc: In member function ‘virtual google::protobuf::uint8* map_sparsification::proto::KeyframingHeuristicsOptions::InternalSerializeWithCachedSizesToArray(bool, google::protobuf::uint8*) const’:
/catkin_ws/build/map_sparsification/compiled_proto/map-sparsification/keyframing-heuristics-options.pb.cc:331:10: warning: unused parameter ‘deterministic’ [-Wunused-parameter]
     bool deterministic, ::google::protobuf::uint8* target) const {
          ^~~~~~~~~~~~~
cd /catkin_ws/build/map_sparsification; catkin build --get-env map_sparsification | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
.............................................................................................................................................................................................
Finished  <<< map_sparsification                              [ 1 minute and 30.8 seconds ]
[build] Summary: 90 of 112 packages succeeded.
[build]   Ignored:   21 packages were skipped or are blacklisted.
[build]   Warnings:  15 packages succeeded with warnings.
[build]   Abandoned: 21 packages were abandoned.
[build]   Failed:    1 packages failed.
_____________________________________________________________________________________________________________________________________________________________________________________________```

**Comment by gforestier27** [comment]
Solved by doing a catkin clean, and then doing `catkin build maplab` before the command above.

**Comment by AbdelrhmanBassiouny** [comment]
Hello,
I had the same issue and doing catkin clean then catkin build maplab didn't solve it for me.
I had to add the following lines of code to "maplab/backend/map-resources/src/resource-conversion.cc" line 590:

```cpp
template <>
void addLabelToPointCloud(
    const uint32_t label, const size_t index,
    resources::VoxbloxColorPointCloud* point_cloud) {
  CHECK_NOTNULL(point_cloud);
  DCHECK_LT(index, point_cloud->points_C->size());
}
```

This is just to be able to build, It doesn't perform anything inside but some checks, I do not know who is trying to call this function.
